yarnPath: ".yarn/releases/yarn-berry.cjs"

cacheFolder: "./.yarn/cache"

changesetBaseRefs:
- "master"
- "origin/master"
- "upstream/master"

changesetIgnorePatterns:
- "**/*.test.{js,ts}"

checksumBehavior: "throw"

compressionLevel: "mixed"

defaultLanguageName: "node"

defaultProtocol: "npm:"

defaultSemverRangePrefix: "^"

deferredVersionFolder: "./.yarn/versions"

enableColors: true

enableGlobalCache: false

enableHyperlinks: true

enableImmutableCache: false

enableInlineBuilds: false

enableProgressBars: true

enableScripts: true

enableTransparentWorkspaces: true